// Code generated by MockGen. DO NOT EDIT.
// Source: ./services/customer_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	models "AntarJemput-Be-C/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCustomerServiceInterface is a mock of CustomerServiceInterface interface.
type MockCustomerServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerServiceInterfaceMockRecorder
}

// MockCustomerServiceInterfaceMockRecorder is the mock recorder for MockCustomerServiceInterface.
type MockCustomerServiceInterfaceMockRecorder struct {
	mock *MockCustomerServiceInterface
}

// NewMockCustomerServiceInterface creates a new mock instance.
func NewMockCustomerServiceInterface(ctrl *gomock.Controller) *MockCustomerServiceInterface {
	mock := &MockCustomerServiceInterface{ctrl: ctrl}
	mock.recorder = &MockCustomerServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerServiceInterface) EXPECT() *MockCustomerServiceInterfaceMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockCustomerServiceInterface) GetAll() ([]models.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]models.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockCustomerServiceInterfaceMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockCustomerServiceInterface)(nil).GetAll))
}

// GetById mocks base method.
func (m *MockCustomerServiceInterface) GetById(id int) (models.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", id)
	ret0, _ := ret[0].(models.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockCustomerServiceInterfaceMockRecorder) GetById(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockCustomerServiceInterface)(nil).GetById), id)
}

// Save mocks base method.
func (m *MockCustomerServiceInterface) Save(customer *models.Customer) (*models.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", customer)
	ret0, _ := ret[0].(*models.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockCustomerServiceInterfaceMockRecorder) Save(customer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockCustomerServiceInterface)(nil).Save), customer)
}
